schema_version: 1
semantics: all_required
required_for_launch: true
files:
- name: exec.bin
  sha1: 5A65B922B562CB1F57DAB51B73151283F0E20C7A
  description: Intellivision Executive ROM (8 KB)
- name: grom.bin
  sha1: F9608BB4AD1CFE3640D02844C7AD8E0BCD974917
  description: Intellivision Graphics ROM (2 KB)
