//! MAME ROM-set name resolution — data model + slim-file parser + merge.
//!
//! Per-arcade-game records (name → description / year / manufacturer /
//! cloneof) consumed by the library ingest pipeline so a `.zip` named
//! `dkong.zip` shows "Donkey Kong" in the library tile instead of the
//! cryptic 8-char filename.
//!
//! Two-layer model (no L2 for arcade games — the listxml IS the
//! canonical curated source, and per-machine YAML curation isn't worth
//! the maintenance load for ~25-30k records):
//!
//! - **L1 — bundled MAME baseline.** Parsed from
//!   `assets/mame-source/mame-games-slim.json`, generated by
//!   `tools/mame-extractor/` against MAME's `-listxml`. Carries the
//!   per-machine description / year / manufacturer / cloneof for every
//!   playable arcade-game machine MAME knows about.
//!
//! - **L3 — operator overrides.** Per-install local edits in SQLite's
//!   `mame_games_overrides` table. Sparse — only fields the operator
//!   actually edited are stored. Operator-facing edit UI deferred to
//!   v2; the table + plumbing ship in v1 so operators with a SQL
//!   client can override individual rows without waiting for the UI.
//!
//! Lookup precedence in [`merge_mame_game`]: L3 wins per-field over L1.
//!
//! This module owns:
//! - The Rust types ([`MameGame`] / [`MameGameOverride`] /
//!   [`MergedMameGame`]).
//! - The slim-file parser ([`parse_mame_games_slim_json`]).
//! - The merge function ([`merge_mame_game`]).
//! - Runtime path resolution ([`resolve_mame_games_slim_path`]).
//! - Hashing helper for bake-on-launch dirty detection
//!   ([`hash_l1_input`]).
//!
//! The SQLite tables + Tauri commands live in `library_db.rs` and
//! `main.rs` respectively — this module is the pure-data layer, mirror
//! of [`crate::system_info`]'s shape.
//!
//! Plan: `C:/Users/Devilchi/.claude/plans/glittery-kindling-blum.md`.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Current `mame-games-slim.json` schema version we know how to parse.
/// The extractor in `tools/mame-extractor/` emits this version today;
/// bumping it requires coordinated changes in both places. Future
/// loaders reject artifacts with a higher schema version rather than
/// silently dropping fields.
pub const MAME_GAMES_SLIM_SCHEMA_VERSION: u32 = 1;

// =====================================================================
// L1 — bundled MAME baseline
// =====================================================================

/// One arcade-game machine's slim record. Hydrated from
/// `assets/mame-source/mame-games-slim.json` and stored in the
/// `mame_games` SQLite table.
///
/// Field shape matches the extractor's [`tools/mame-extractor/src/
/// main.rs::ArcadeGameRecord`] — JSON wire compatibility is what lets
/// us re-bake from a regenerated slim file without intermediate
/// transformation. Fields use camelCase on the wire so the Tauri
/// frontend can consume them directly.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MameGame {
    /// MAME machine name. Matches the operator's `.zip` filename stem
    /// (`dkong.zip` → `"dkong"`). Lowercase by MAME convention.
    pub name: String,
    /// Human title from MAME's `<description>` (`"Donkey Kong (US set 1)"`,
    /// `"Street Fighter II': Champion Edition (World 920313)"`). Always
    /// present — the extractor filter rejects records with empty
    /// descriptions.
    pub description: String,
    /// Release year as a string (MAME emits this; not always a 4-digit
    /// number — some MAME entries say `"19??"` for unknown years).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    /// Manufacturer string (`"Nintendo"`, `"Capcom"`, `"Konami"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    /// Parent ROM-set's name when this machine is a clone. `None` for
    /// parents. Operators with `sf2ce.zip` get `cloneof: Some("sf2")`,
    /// so future grouping features can link parent + clones in the UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cloneof: Option<String>,
}

/// Top-level shape of `mame-games-slim.json`. The extractor emits
/// this; the loader parses it. `schema_version` lets the loader
/// reject incompatible bumps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlimMameGames {
    pub mame_version: String,
    pub schema_version: u32,
    pub machines: Vec<MameGame>,
}

// =====================================================================
// L3 — operator overrides
// =====================================================================

/// Sparse per-machine override. Each non-None field replaces the
/// L1 value at merge time. Stored in `mame_games_overrides`; rows
/// only exist when the operator has at least one non-default field
/// (a default-constructed override triggers a DELETE rather than an
/// UPSERT — same convention as [`crate::system_info::SystemInfoOverride`]).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MameGameOverride {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cloneof: Option<String>,
}

impl MameGameOverride {
    /// True when every override field is None — used by the upsert
    /// path to decide between INSERT/UPDATE and DELETE.
    pub fn is_empty(&self) -> bool {
        self.description.is_none()
            && self.year.is_none()
            && self.manufacturer.is_none()
            && self.cloneof.is_none()
    }
}

// =====================================================================
// Merged lookup result
// =====================================================================

/// Result of merging L1 + L3 for one machine. Returned by
/// `lookup_mame_game` (Tauri command); consumed by the frontend
/// `resolveMameTitles` hook at ingest time.
///
/// `has_local_edits` is true iff the L3 row exists with at least one
/// non-None field. Frontend uses this for the "Edited" badge in any
/// future override UI.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MergedMameGame {
    pub name: String,
    pub description: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cloneof: Option<String>,
    pub has_local_edits: bool,
}

/// Merge L1 baseline with optional L3 override. L3 wins per-field;
/// `description` falls back to L1 when L3 leaves it None (description
/// is the only required field — the merged record must carry one).
pub fn merge_mame_game(l1: MameGame, l3: Option<MameGameOverride>) -> MergedMameGame {
    let has_local_edits = l3.as_ref().map(|o| !o.is_empty()).unwrap_or(false);
    let l3 = l3.unwrap_or_default();
    MergedMameGame {
        name: l1.name,
        description: l3.description.unwrap_or(l1.description),
        year: l3.year.or(l1.year),
        manufacturer: l3.manufacturer.or(l1.manufacturer),
        cloneof: l3.cloneof.or(l1.cloneof),
        has_local_edits,
    }
}

// =====================================================================
// Slim-file parser
// =====================================================================

/// Parse `assets/mame-source/mame-games-slim.json`. Returns the parsed
/// records (already sorted ascending by `name` per the extractor's
/// output convention). Missing file returns `Ok(Vec::new())` — the
/// bake-on-launch path treats "no slim file" as "L1 empty"; lookups
/// fall through to the legacy `mame_titles` path or to the filename.
pub fn parse_mame_games_slim_json(path: &Path) -> Result<Vec<MameGame>, String> {
    let bytes = match std::fs::read(path) {
        Ok(b) => b,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(format!("read {}: {e}", path.display())),
    };
    let slim: SlimMameGames = serde_json::from_slice(&bytes)
        .map_err(|e| format!("parse {}: {e}", path.display()))?;
    if slim.schema_version > MAME_GAMES_SLIM_SCHEMA_VERSION {
        return Err(format!(
            "mame-games-slim.json schema_version {} exceeds what this build understands ({})",
            slim.schema_version, MAME_GAMES_SLIM_SCHEMA_VERSION
        ));
    }
    Ok(slim.machines)
}

// =====================================================================
// File-tree resolver
// =====================================================================

/// Locate `assets/mame-source/mame-games-slim.json` at runtime.
/// Reuses [`crate::system_info::resolve_assets_mame_source_dir`] — the
/// new artifact lives next to `listxml-slim.json`. Returns `None` when
/// the directory itself can't be found; the bake-on-launch caller
/// degrades gracefully.
pub fn resolve_mame_games_slim_path() -> Option<PathBuf> {
    crate::system_info::resolve_assets_mame_source_dir()
        .map(|d| d.join("mame-games-slim.json"))
}

// =====================================================================
// Hashing — bake-on-launch dirty detection
// =====================================================================

/// Hash the bundled L1 slim file so the bake-on-launch path can detect
/// when a rebake is needed. Mirrors
/// [`crate::system_info::hash_l1_l2_inputs`]'s shape — same SHA-1 with
/// 16-char hex prefix, same `MISSING:`-prefix encoding for absent
/// files so a regenerated slim flips the hash even when the previous
/// run had no slim at all.
pub fn hash_l1_input(slim_path: &Path) -> String {
    use sha1::{Digest, Sha1};
    let mut hasher = Sha1::new();
    match std::fs::read(slim_path) {
        Ok(bytes) => {
            hasher.update(b"FILE:");
            hasher.update(&bytes);
        }
        Err(_) => {
            hasher.update(b"MISSING:");
            hasher.update(slim_path.to_string_lossy().as_bytes());
        }
    }
    let digest = hasher.finalize();
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
    hex[..16].to_string()
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_SLIM_JSON: &str = r#"{
        "mame_version": "0.288",
        "schema_version": 1,
        "machines": [
            {"name": "dkong", "description": "Donkey Kong (US set 1)", "year": "1981", "manufacturer": "Nintendo"},
            {"name": "sf2", "description": "Street Fighter II: The World Warrior", "year": "1991", "manufacturer": "Capcom"},
            {"name": "sf2ce", "description": "Street Fighter II': Champion Edition", "year": "1992", "manufacturer": "Capcom", "cloneof": "sf2"}
        ]
    }"#;

    fn write_sample_slim() -> PathBuf {
        let path = std::env::temp_dir().join(format!(
            "mame-games-slim-test-{}.json",
            std::process::id()
        ));
        std::fs::write(&path, SAMPLE_SLIM_JSON).unwrap();
        path
    }

    #[test]
    fn parses_slim_json_with_all_three_records() {
        let path = write_sample_slim();
        let records = parse_mame_games_slim_json(&path).expect("parse must succeed");
        let _ = std::fs::remove_file(&path);
        assert_eq!(records.len(), 3);
        assert_eq!(records[0].name, "dkong");
        assert_eq!(records[0].description, "Donkey Kong (US set 1)");
        assert_eq!(records[0].year.as_deref(), Some("1981"));
        assert_eq!(records[0].manufacturer.as_deref(), Some("Nintendo"));
        assert_eq!(records[0].cloneof, None);
        assert_eq!(records[2].name, "sf2ce");
        assert_eq!(records[2].cloneof.as_deref(), Some("sf2"));
    }

    #[test]
    fn missing_slim_file_returns_empty_not_error() {
        let path = std::env::temp_dir().join(format!(
            "mame-games-slim-missing-{}.json",
            std::process::id()
        ));
        let records = parse_mame_games_slim_json(&path).expect("missing must succeed");
        assert!(records.is_empty());
    }

    #[test]
    fn future_schema_version_rejected() {
        let path = std::env::temp_dir().join(format!(
            "mame-games-slim-future-{}.json",
            std::process::id()
        ));
        std::fs::write(
            &path,
            r#"{"mame_version":"0.99","schema_version":999,"machines":[]}"#,
        )
        .unwrap();
        let result = parse_mame_games_slim_json(&path);
        let _ = std::fs::remove_file(&path);
        assert!(result.is_err(), "future schema must be rejected");
        let msg = result.unwrap_err();
        assert!(msg.contains("schema_version"), "error must mention schema_version");
    }

    #[test]
    fn merge_l1_only_keeps_baseline_values() {
        let l1 = MameGame {
            name: "dkong".into(),
            description: "Donkey Kong".into(),
            year: Some("1981".into()),
            manufacturer: Some("Nintendo".into()),
            cloneof: None,
        };
        let merged = merge_mame_game(l1, None);
        assert_eq!(merged.description, "Donkey Kong");
        assert_eq!(merged.year.as_deref(), Some("1981"));
        assert_eq!(merged.manufacturer.as_deref(), Some("Nintendo"));
        assert!(!merged.has_local_edits);
    }

    #[test]
    fn merge_l3_per_field_wins_and_sets_has_local_edits() {
        let l1 = MameGame {
            name: "sf2ce".into(),
            description: "Street Fighter II': Champion Edition (World 920313)".into(),
            year: Some("1992".into()),
            manufacturer: Some("Capcom".into()),
            cloneof: Some("sf2".into()),
        };
        // Operator polishes the description; year + manufacturer ride
        // L1 through unchanged.
        let l3 = MameGameOverride {
            name: "sf2ce".into(),
            description: Some("SF II Champion Edition".into()),
            ..Default::default()
        };
        let merged = merge_mame_game(l1, Some(l3));
        assert_eq!(merged.description, "SF II Champion Edition");
        assert_eq!(merged.year.as_deref(), Some("1992"));
        assert_eq!(merged.manufacturer.as_deref(), Some("Capcom"));
        assert_eq!(merged.cloneof.as_deref(), Some("sf2"));
        assert!(merged.has_local_edits);
    }

    #[test]
    fn merge_empty_l3_does_not_set_has_local_edits() {
        // Empty override (every field None) — should NOT mark
        // has_local_edits true. Mirrors the table-row-deleted state.
        let l1 = MameGame {
            name: "dkong".into(),
            description: "Donkey Kong".into(),
            ..Default::default()
        };
        let l3 = MameGameOverride { name: "dkong".into(), ..Default::default() };
        let merged = merge_mame_game(l1, Some(l3));
        assert!(!merged.has_local_edits);
    }

    #[test]
    fn override_is_empty_detects_pure_default() {
        assert!(MameGameOverride { name: "x".into(), ..Default::default() }.is_empty());
        assert!(!MameGameOverride {
            name: "x".into(),
            description: Some("y".into()),
            ..Default::default()
        }
        .is_empty());
    }

    #[test]
    fn hash_changes_when_file_changes() {
        let tmp = std::env::temp_dir().join(format!(
            "mame-games-hash-{}.json",
            std::process::id()
        ));
        std::fs::write(&tmp, r#"{"a":1}"#).unwrap();
        let h1 = hash_l1_input(&tmp);
        std::fs::write(&tmp, r#"{"a":2}"#).unwrap();
        let h2 = hash_l1_input(&tmp);
        let _ = std::fs::remove_file(&tmp);
        assert_ne!(h1, h2, "byte change must flip the hash");
    }

    #[test]
    fn hash_missing_file_is_stable_and_distinct_from_present() {
        let missing = std::env::temp_dir().join(format!(
            "mame-games-hash-missing-{}.json",
            std::process::id()
        ));
        let present = std::env::temp_dir().join(format!(
            "mame-games-hash-present-{}.json",
            std::process::id()
        ));
        std::fs::write(&present, "{}").unwrap();
        let h_missing_1 = hash_l1_input(&missing);
        let h_missing_2 = hash_l1_input(&missing);
        let h_present = hash_l1_input(&present);
        let _ = std::fs::remove_file(&present);
        // Missing hash is stable (same input path → same hash).
        assert_eq!(h_missing_1, h_missing_2);
        // Missing ≠ present.
        assert_ne!(h_missing_1, h_present);
    }
}
