//! System Info Panel v1 — data model + slim-file parsers + merge.
//!
//! Per-system records describing the hardware (manufacturer, CPU, sound,
//! resolution, refresh rate, peripherals, etc.) shown on the Retroverse
//! HOME tab's right pane. Replaces the hand-typed-5-of-45-systems
//! `frontend/src/routes/retroverse/systemMetadataStubs.ts` with a real
//! three-layer data model:
//!
//! - **L1 — MAME baseline.** Parsed from `assets/mame-source/`'s
//!   `listxml-slim.json` (structured fields) + `history-slim.xml`
//!   (`<text>` description prose). Generated by `tools/mame-extractor/`
//!   against MAME's `-listxml` + arcade-history.com's `history.xml`.
//!   Carries the per-system rows the OA team can never write themselves
//!   — CPU clocks, chip names, raw refresh rates.
//!
//! - **L2 — OA curated.** Per-system YAML at
//!   `docs/cores/<id>/system-info.yaml`. Hand-authored by the OA team
//!   for fields MAME doesn't expose (release date with month/day,
//!   units sold, generation, peripheral names + glyphs, hero blurbs)
//!   AND for polishing L1 fields where MAME emits awkward strings.
//!
//! - **L3 — Operator edits.** Per-install local overrides in SQLite's
//!   `system_info_overrides` table. Operator-facing edit UI lands in
//!   Phase 4 (per-system Settings drill-in).
//!
//! [`merge_system_info`] resolves the three layers field-by-field —
//! L3 wins per-field, L2 next, L1 fallback. Same shape `merge_game_info`
//! uses for per-game data.
//!
//! This module owns:
//!
//! - The Rust types ([`SystemInfoMame`] / [`SystemInfoCurated`] /
//!   [`SystemInfoOverride`] / [`MergedSystemInfo`] / [`Peripheral`] /
//!   [`SystemInfoMeta`]).
//! - The slim-file parsers ([`parse_listxml_slim_json`] /
//!   [`parse_history_slim_xml`] / [`parse_system_info_yaml`]).
//! - The merge function ([`merge_system_info`]).
//! - Runtime path resolution ([`resolve_assets_mame_source_dir`] /
//!   [`resolve_docs_cores_dir`]) — twin of `game_info`'s resolver,
//!   walking the exe-dir → source-tree fallback chain.
//! - Hashing helpers for the bake-on-launch dirty detection
//!   ([`hash_l1_l2_inputs`]).
//!
//! The SQLite tables (Phase 2 §5) + Tauri commands live in
//! `library_db.rs` and `main.rs` respectively — this module is the
//! pure-data layer.
//!
//! Plan: `docs/PLANS/system-info-panel-v1.md`.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// Schema version embedded in every L2 YAML's `meta.schema_version`
/// field. Bump only on breaking field changes; consumers should
/// reject records with `schema_version > CURRENT_SCHEMA_VERSION`
/// rather than silently rendering possibly-malformed data.
pub const CURRENT_SCHEMA_VERSION: u32 = 1;

// =====================================================================
// L1 — MAME baseline
// =====================================================================

/// One MAME machine's slim record, after the extractor in
/// `tools/mame-extractor/` filtered MAME's `-listxml`. Hydrated from
/// `assets/mame-source/listxml-slim.json` (structured fields) +
/// `assets/mame-source/history-slim.xml` (description prose).
///
/// Multiple OA slugs can target the same underlying MAME machine
/// (`tg16` + `pce-cd` both → MAME's `pce`); the extractor's fan-out
/// produces one record per slug, sharing field values.
///
/// All fields except `system_id` + `machine_name` are optional —
/// MAME doesn't reliably populate clocks, chip names, or display
/// attributes across every console driver. Missing values surface as
/// "L1 has nothing here; check L2 next." See [`merge_system_info`]
/// for the precedence wiring.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct SystemInfoMame {
    /// OA system slug (`"nes"`, `"tg16"`, `"pce-cd"`, …) — joins to
    /// the per-system theme registry on the frontend and the
    /// `docs/cores/<id>/` directory layout.
    pub system_id: String,
    /// MAME machine driver name (`"nes"`, `"pce"`, `"a2600"`). Kept
    /// for diagnostic surfaces — operators occasionally want to know
    /// which MAME machine a record traces back to. Optional because
    /// L1-stub rows (systems MAME doesn't cover — `3do`, `msx`,
    /// `msx2`, DOSBox / ScummVM) don't have one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub machine_name: Option<String>,
    /// Release year as a 4-digit string, sourced from MAME's
    /// `<year>` element. The L2 YAML can polish this to a full
    /// "October 29, 1988" form.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub year: Option<String>,
    /// Manufacturer string from MAME's `<manufacturer>` element.
    /// Often more verbose than the OA-facing name (e.g. "NEC / Hudson
    /// Soft" for PCE); L2 can override with a cleaner form.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    /// Formatted CPU string from the first `<chip type="cpu">`,
    /// e.g. "Ricoh RP2A03G @ 1.79 MHz". The extractor handles the
    /// Hz → MHz conversion.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    /// Formatted sound chip string from the first `<chip type="audio">`.
    /// MAME often emits the same chip name for both CPU + audio on
    /// classic consoles (NES, PCE); L2 typically polishes this.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    /// First `<display>` element's width × height, e.g. "256 × 240".
    /// Multi-screen machines surface the first screen only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    /// First `<display>`'s `refresh` attribute, formatted "60.10 Hz".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_rate: Option<String>,
    /// `<input players="…">` integer. Converted to a human-friendly
    /// string at merge time when L2 + L3 are both empty
    /// ("1 Player" / "2 Players" / "Up to 4 Players").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_players: Option<u32>,
    /// Raw MAME control-kind strings (`"joy"`, `"lightgun"`,
    /// `"trackball"`) from `<input>/<control type="…">`. Not shown to
    /// operators directly — the L2 `peripherals` list is the
    /// operator-facing surface. Reserved for future filters ("show
    /// only systems with lightgun support").
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub peripheral_hints: Vec<String>,
    /// Description prose from `history.xml`'s `<text>` element. Empty
    /// when the system has no `history.xml` entry (3DO / MSX / MSX2 /
    /// DOSBox / ScummVM / PSP / PS2 / NDS / GameCube — see the slim
    /// file's `# WARNING` line if the maintainer didn't supply
    /// history.xml at bump time).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

/// Top-level shape of `assets/mame-source/listxml-slim.json` —
/// what the extractor in `tools/mame-extractor/` emits.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SlimListxml {
    /// MAME version string the bump was generated against
    /// (e.g. `"0.288(mame0288)"`).
    pub mame_version: String,
    /// One record per OA system slug. Fan-out happens in the
    /// extractor; this Vec is already per-slug, not per-machine.
    pub systems: Vec<SystemInfoMame>,
}

// =====================================================================
// L2 — OA curated
// =====================================================================

/// Hand-curated per-system YAML at `docs/cores/<id>/system-info.yaml`.
/// One record per file. Fields the OA team writes by hand for systems
/// MAME's data can't supply (release dates with month/day, units sold,
/// peripheral names + glyphs, hero blurbs) and polish for fields MAME
/// emits awkwardly.
///
/// Every field is optional except `system_id`; an L2 YAML that only
/// sets `blurb` is perfectly fine — every other field flows through
/// from L1 or stays "—" in the UI.
///
/// Field grouping mirrors the panel's three sections (SYSTEM
/// INFORMATION / TECHNICAL DETAILS / hero extras).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SystemInfoCurated {
    /// OA system slug — must match the directory name under
    /// `docs/cores/`. Mandatory.
    ///
    /// Serde rename map (struct-level + per-field aliases): outputs
    /// camelCase for the Tauri JSON response the frontend expects,
    /// while every snake_case YAML key authored in
    /// `docs/cores/<id>/system-info.yaml` still parses via the
    /// per-field `alias` attributes below. Net effect: YAML stays in
    /// the operator-friendly snake_case convention; the wire format
    /// matches MergedSystemInfo / SystemInfoOverride.
    #[serde(alias = "system_id")]
    pub system_id: String,

    // --- SYSTEM INFORMATION (12 fields) -----------------------------

    /// Cleaner manufacturer name, e.g. "Nintendo" instead of MAME's
    /// "NEC / Hudson Soft". Overrides L1.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    /// "Home Console" / "Handheld" / "Arcade" — editorial; MAME
    /// doesn't classify this way. YAML key is `type` (single word);
    /// JSON wire key is `systemType` for consistency with
    /// MergedSystemInfo + SystemInfoOverride.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "type")]
    pub system_type: Option<String>,
    /// "3rd Generation" / "4th Generation" — editorial.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation: Option<String>,
    /// Full release date — "October 29, 1988". L1 has the year only.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "release_date")]
    pub release_date: Option<String>,
    /// Discontinuation date — entirely L2 (never in MAME).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discontinued: Option<String>,
    /// Lifetime units sold ("49.10 Million"). Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "units_sold")]
    pub units_sold: Option<String>,
    /// Media format ("Cartridge", "CD-ROM", "DVD-ROM"). MAME-→L2 polish.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    /// Polished CPU string ("Ricoh 5A22 @ 3.58 MHz"). Overrides L1.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    /// Polished sound chip ("Sony SPC700"). Overrides L1.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    /// Polished resolution ("256 x 224"). Overrides L1's emit which
    /// sometimes reflects pixel-clock dimensions rather than the
    /// framebuffer.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    /// Color palette ("32,768 Colors", "54 Colors"). Not in MAME's
    /// `-listxml` for home consoles; entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "color_palette")]
    pub color_palette: Option<String>,
    /// Source pixel ratio framing ("8:7 (4:3)"). Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "display_ratio")]
    pub display_ratio: Option<String>,

    // --- TECHNICAL DETAILS (9 fields) -------------------------------

    /// Bit-width architecture ("8-Bit" / "16-Bit"). Editorial.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    /// Polished max-players string ("1-2 Players"). Overrides L1's
    /// integer (which formats as "N Players" by default at merge).
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "max_players")]
    pub max_players: Option<String>,
    /// Free-form multiplayer description ("2 local; 4 with multitap").
    /// Replaces the old binary "Co-Op Support: Yes/No" framing from
    /// `systemMetadataStubs.ts`. Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multiplayer: Option<String>,
    /// Region ("NTSC / PAL"). MAME-→L2 polish.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Storage ("Cartridge (4MB Max)"). Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
    /// RAM size ("128KB"). Sometimes in MAME; treat as editorial.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ram: Option<String>,
    /// Video output formats ("Composite / RGB"). Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "video_output")]
    pub video_output: Option<String>,
    /// Display aspect ("4:3"). Entirely L2.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "aspect_ratio")]
    pub aspect_ratio: Option<String>,
    /// Polished refresh rate ("60 Hz" without decimals).
    /// Overrides L1's emit ("60.10 Hz").
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "refresh_rate")]
    pub refresh_rate: Option<String>,

    // --- PERIPHERALS ------------------------------------------------

    /// Operator-facing peripheral list with display names + glyphs.
    /// L1's `peripheral_hints` (raw MAME control kinds) doesn't feed
    /// the UI directly — only the curated list does.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub peripherals: Vec<Peripheral>,

    // --- Hero extras (L2-only, never in MAME) -----------------------

    /// Country-of-origin flag emoji ("🇺🇸" / "🇯🇵") shown next to the
    /// release date in the HOME tab's hero.
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "release_flag")]
    pub release_flag: Option<String>,
    /// Short subtitle under the system name in the hero
    /// ("16-BIT HOME CONSOLE").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tagline: Option<String>,
    /// 2-4 sentence curator description shown below the release line.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blurb: Option<String>,
    /// Compact subline shown beneath the system name in the SYSTEMS
    /// sidebar ("16-BIT · 1990").
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sidebar_subline")]
    pub sidebar_subline: Option<String>,

    /// Per-record bookkeeping (schema version, last-edit date,
    /// contributors). Default-populated when absent.
    #[serde(default)]
    pub meta: SystemInfoMeta,
}

/// One operator-facing peripheral row. The frontend renders these as
/// `glyph name` lines under SUPPORTED PERIPHERALS.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct Peripheral {
    /// Display name ("Zapper" / "Super Scope" / "Multitap (X4)").
    pub name: String,
    /// Single character / emoji glyph rendered next to the name.
    /// Authors paste emoji directly into the YAML.
    pub glyph: String,
}

/// Per-record bookkeeping. All fields default-populated so a record
/// authored without an explicit `meta:` block still parses cleanly.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct SystemInfoMeta {
    /// Schema version for forward compatibility. Defaults to 1.
    #[serde(default = "default_schema_version")]
    pub schema_version: u32,
    /// ISO 8601 date of the last edit ("2026-05-31"). None when
    /// the record has never been touched after creation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<String>,
    /// Attribution list for v2's hand-curated content layer.
    #[serde(default)]
    pub contributors: Vec<String>,
}

impl Default for SystemInfoMeta {
    fn default() -> Self {
        Self {
            schema_version: CURRENT_SCHEMA_VERSION,
            last_updated: None,
            contributors: Vec::new(),
        }
    }
}

fn default_schema_version() -> u32 {
    CURRENT_SCHEMA_VERSION
}

// =====================================================================
// L3 — operator local overrides
// =====================================================================

/// Per-install operator edits — Layer 3. Every L2 field plus the
/// `peripherals` list and hero extras can be overridden. `None` means
/// "no override, fall through to L2 → L1"; `Some(value)` wins over
/// both lower layers, with `Some("")` representing an explicit clear.
///
/// Stored in SQLite `system_info_overrides`, keyed by `system_id`.
/// Phase 4 wires the per-system Settings drill-in edit UI; the v1
/// surface is form-row-per-field with provenance badges.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SystemInfoOverride {
    // SYSTEM INFORMATION
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discontinued: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units_sold: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color_palette: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_ratio: Option<String>,

    // TECHNICAL DETAILS
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_players: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multiplayer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ram: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub video_output: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_rate: Option<String>,

    // PERIPHERALS — Some(vec) replaces the L2 list entirely;
    // Some(vec![]) is an explicit "operator says no peripherals."
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub peripherals: Option<Vec<Peripheral>>,

    // Hero extras
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub release_flag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tagline: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blurb: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sidebar_subline: Option<String>,
}

impl SystemInfoOverride {
    /// True when no field carries a meaningful edit — used to decide
    /// whether to DELETE the override row vs UPSERT it. Keeps the
    /// table sparse: a default-constructed override doesn't pollute
    /// the DB.
    pub fn is_empty(&self) -> bool {
        self.manufacturer.is_none()
            && self.system_type.is_none()
            && self.generation.is_none()
            && self.release_date.is_none()
            && self.discontinued.is_none()
            && self.units_sold.is_none()
            && self.media.is_none()
            && self.cpu.is_none()
            && self.sound.is_none()
            && self.resolution.is_none()
            && self.color_palette.is_none()
            && self.display_ratio.is_none()
            && self.architecture.is_none()
            && self.max_players.is_none()
            && self.multiplayer.is_none()
            && self.region.is_none()
            && self.storage.is_none()
            && self.ram.is_none()
            && self.video_output.is_none()
            && self.aspect_ratio.is_none()
            && self.refresh_rate.is_none()
            && self.peripherals.is_none()
            && self.release_flag.is_none()
            && self.tagline.is_none()
            && self.blurb.is_none()
            && self.sidebar_subline.is_none()
    }
}

// =====================================================================
// Merged shape — what the UI consumes
// =====================================================================

/// Final per-system record after field-typed L1 + L2 + L3 merge. The
/// shape `get_system_info` returns to the frontend; HomePage hero +
/// SystemInfoPanel right pane render directly from this struct.
///
/// Naming uses camelCase to match the Tauri command return-type
/// convention the frontend's `useMedia` / `useLibrary` hooks already
/// expect.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MergedSystemInfo {
    /// Echo of the input slug.
    pub system_id: String,

    // SYSTEM INFORMATION
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub system_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub release_date: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discontinued: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub units_sold: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub media: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cpu: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sound: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub color_palette: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub display_ratio: Option<String>,

    // TECHNICAL DETAILS
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub architecture: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_players: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub multiplayer: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub storage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ram: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub video_output: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refresh_rate: Option<String>,

    // PERIPHERALS — final merged list. Always populated (could be
    // empty), so frontend doesn't need to null-check.
    #[serde(default)]
    pub peripherals: Vec<Peripheral>,
    /// Raw MAME control-kind hints. L1-only; not editable through
    /// L2/L3. Reserved for future filter UIs.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub peripheral_hints: Vec<String>,

    // Hero extras
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub release_flag: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tagline: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub blurb: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sidebar_subline: Option<String>,

    /// `history.xml` prose, L1-only. Renders in the per-system
    /// Settings drill-in as "MAME's bio". Long; not shown on HOME.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// True when the operator's L3 override carries at least one
    /// non-default field — drives a "(edited)" indicator in the
    /// per-system Settings drill-in.
    #[serde(default)]
    pub has_local_edits: bool,
}

/// Field-typed merge of the three layers. Each scalar resolves L3 → L2
/// → L1 → None; peripherals follow the override-replaces-file semantics
/// (`Some(vec)` from L3 wins, else L2's list, else derived empty).
///
/// `mame_max_players` (the L1 integer) is formatted as a string only
/// when L2 + L3 don't supply one — so the UI consistently sees a
/// string-typed `max_players` regardless of which layer won.
pub fn merge_system_info(
    system_id: &str,
    mame: Option<&SystemInfoMame>,
    curated: Option<&SystemInfoCurated>,
    ov: &SystemInfoOverride,
) -> MergedSystemInfo {
    macro_rules! resolve {
        ($field:ident) => {
            ov.$field
                .clone()
                .or_else(|| curated.and_then(|c| c.$field.clone()))
                .or_else(|| mame.and_then(|m| m.$field.clone()))
        };
        // Variant for fields curated has but L1 doesn't.
        ($field:ident, l2_only) => {
            ov.$field
                .clone()
                .or_else(|| curated.and_then(|c| c.$field.clone()))
        };
    }

    let manufacturer = resolve!(manufacturer);
    let cpu = resolve!(cpu);
    let sound = resolve!(sound);
    let resolution = resolve!(resolution);
    let refresh_rate = resolve!(refresh_rate);
    let media = resolve!(media, l2_only);
    let region = resolve!(region, l2_only); // MAME has region per-machine but
                                             // listxml emits it inconsistently;
                                             // treat as L2-driven for v1.

    // L1 carries max_players as Option<u32>; format only when both
    // higher layers leave it empty. format_max_players is the
    // fallback bridge between integer + string layers.
    let max_players = ov
        .max_players
        .clone()
        .or_else(|| curated.and_then(|c| c.max_players.clone()))
        .or_else(|| mame.and_then(|m| m.max_players).map(format_max_players));

    // Peripheral list — L3 replaces, L2 owns operator-facing copy;
    // L1's peripheral_hints don't surface here (those are the raw
    // MAME kinds, exposed separately as `peripheral_hints` on the
    // merged record for future filter consumers).
    let peripherals = if let Some(p) = ov.peripherals.clone() {
        p
    } else {
        curated.map(|c| c.peripherals.clone()).unwrap_or_default()
    };

    let peripheral_hints = mame
        .map(|m| m.peripheral_hints.clone())
        .unwrap_or_default();

    let has_local_edits = !ov.is_empty();

    MergedSystemInfo {
        system_id: system_id.to_string(),
        manufacturer,
        system_type: resolve!(system_type, l2_only),
        generation: resolve!(generation, l2_only),
        release_date: ov.release_date.clone().or_else(|| {
            curated
                .and_then(|c| c.release_date.clone())
                .or_else(|| mame.and_then(|m| m.year.clone()))
        }),
        discontinued: resolve!(discontinued, l2_only),
        units_sold: resolve!(units_sold, l2_only),
        media,
        cpu,
        sound,
        resolution,
        color_palette: resolve!(color_palette, l2_only),
        display_ratio: resolve!(display_ratio, l2_only),
        architecture: resolve!(architecture, l2_only),
        max_players,
        multiplayer: resolve!(multiplayer, l2_only),
        region,
        storage: resolve!(storage, l2_only),
        ram: resolve!(ram, l2_only),
        video_output: resolve!(video_output, l2_only),
        aspect_ratio: resolve!(aspect_ratio, l2_only),
        refresh_rate,
        peripherals,
        peripheral_hints,
        release_flag: resolve!(release_flag, l2_only),
        tagline: resolve!(tagline, l2_only),
        blurb: resolve!(blurb, l2_only),
        sidebar_subline: resolve!(sidebar_subline, l2_only),
        description: mame.and_then(|m| m.description.clone()),
        has_local_edits,
    }
}

/// Format L1's raw player-count integer into a human-friendly string.
/// Only consulted when neither L2 nor L3 supplied `max_players`.
fn format_max_players(n: u32) -> String {
    match n {
        0 => "—".to_string(),
        1 => "1 Player".to_string(),
        n => format!("Up to {n} Players"),
    }
}

// =====================================================================
// Parsers — slim files (L1) + per-system YAML (L2)
// =====================================================================

/// Parse `assets/mame-source/listxml-slim.json`. Returns the full
/// slim record with the per-slug systems Vec. Bake-on-launch path
/// passes this directly into the SQLite L1 writer.
pub fn parse_listxml_slim_json(content: &str) -> Result<SlimListxml, String> {
    serde_json::from_str(content).map_err(|e| format!("parse listxml-slim.json: {e}"))
}

/// Parse `assets/mame-source/history-slim.xml` and return a map of
/// MAME machine name → description text. Multi-machine `<systems>`
/// blocks emit one map entry per machine (so `nes` + `nespal` both
/// route to the same description); the bake-on-launch path joins on
/// machine_name from the L1 record.
///
/// The expected upstream shape is:
///
/// ```xml
/// <entry>
///   <systems>
///     <system name="nes" game="no" />
///     <system name="nespal" game="no" />
///   </systems>
///   <text>Console published 41 years ago: ...</text>
/// </entry>
/// ```
///
/// Returns an empty map when the file is the header-only placeholder
/// (no `<entry>` blocks).
pub fn parse_history_slim_xml(content: &str) -> Result<HashMap<String, String>, String> {
    use quick_xml::events::Event;
    use quick_xml::Reader;

    let mut out: HashMap<String, String> = HashMap::new();
    let mut reader = Reader::from_str(content);
    reader.config_mut().trim_text(false);
    let mut buf = Vec::new();

    // State machine. `current_entry_machines` collects the
    // `<systems>/<system name="…">` names; `current_text` accumulates
    // the `<text>` body. On `</entry>`, every machine name in
    // current_entry_machines points at current_text.
    let mut in_entry = false;
    let mut in_systems = false;
    let mut in_text = false;
    let mut current_entry_machines: Vec<String> = Vec::new();
    let mut current_text = String::new();

    loop {
        let evt = reader
            .read_event_into(&mut buf)
            .map_err(|e| format!("reading history-slim.xml: {e}"))?;
        match evt {
            Event::Start(ref e) => {
                let name = e.name();
                let tag = std::str::from_utf8(name.as_ref()).unwrap_or("");
                match tag {
                    "entry" => {
                        in_entry = true;
                        current_entry_machines.clear();
                        current_text.clear();
                    }
                    "systems" if in_entry => {
                        in_systems = true;
                    }
                    "text" if in_entry => {
                        in_text = true;
                        current_text.clear();
                    }
                    _ => {}
                }
            }
            Event::Empty(ref e) | Event::Start(ref e) if in_systems => {
                // `<system name="…"/>` — could be Start (rare, with
                // child content) or Empty (the common self-closing
                // form). Both routes record the name.
                let name = e.name();
                let tag = std::str::from_utf8(name.as_ref()).unwrap_or("");
                if tag == "system" {
                    for a in e.attributes() {
                        let Ok(a) = a else { continue };
                        if a.key.as_ref() == b"name" {
                            if let Ok(v) = a.unescape_value() {
                                current_entry_machines.push(v.into_owned());
                            }
                            break;
                        }
                    }
                }
            }
            Event::Text(ref t) if in_text => {
                if let Ok(s) = t.unescape() {
                    current_text.push_str(&s);
                }
            }
            Event::CData(ref t) if in_text => {
                // CDATA preserves the raw bytes; convert to str.
                if let Ok(s) = std::str::from_utf8(t.as_ref()) {
                    current_text.push_str(s);
                }
            }
            Event::End(ref e) => {
                let name = e.name();
                let tag = std::str::from_utf8(name.as_ref()).unwrap_or("");
                match tag {
                    "systems" => in_systems = false,
                    "text" => in_text = false,
                    "entry" if in_entry => {
                        let trimmed = current_text.trim().to_string();
                        if !trimmed.is_empty() {
                            for m in &current_entry_machines {
                                out.insert(m.clone(), trimmed.clone());
                            }
                        }
                        in_entry = false;
                        current_entry_machines.clear();
                        current_text.clear();
                    }
                    _ => {}
                }
            }
            Event::Eof => break,
            _ => {}
        }
        buf.clear();
    }

    Ok(out)
}

/// Parse a `docs/cores/<id>/system-info.yaml` file. Returns `None`
/// when the content is empty / whitespace-only (a no-op file).
/// Malformed YAML returns an Err so the maintainer running
/// `cargo test` sees the failure rather than silently dropping the
/// L2 row.
pub fn parse_system_info_yaml(content: &str) -> Result<Option<SystemInfoCurated>, String> {
    let trimmed = content.trim();
    if trimmed.is_empty() {
        return Ok(None);
    }
    let record: SystemInfoCurated = serde_yaml::from_str(trimmed)
        .map_err(|e| format!("parse system-info.yaml: {e}"))?;
    Ok(Some(record))
}

// =====================================================================
// File-tree resolvers + L2 directory walk
// =====================================================================

/// Resolve the `assets/mame-source/` directory at runtime. Walks two
/// candidate locations in priority order; returns the first one that
/// exists. Mirrors the [`game_info::resolve_docs_cores_dir`] pattern.
///
/// Order:
/// 1. `<exe_dir>/assets/mame-source/` — production install path.
///    The build / packaging pipeline copies the slim files here next
///    to the binary.
/// 2. `<CARGO_MANIFEST_DIR>/../../assets/mame-source/` — source-tree
///    path for `cargo run` + `cargo tauri dev` + `cargo test`.
pub fn resolve_assets_mame_source_dir() -> Option<PathBuf> {
    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            let p = exe_dir.join("assets").join("mame-source");
            if p.is_dir() {
                return Some(p);
            }
        }
    }
    let dev = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("assets")
        .join("mame-source");
    if dev.is_dir() {
        return Some(dev);
    }
    None
}

/// Resolve the `docs/cores/` directory at runtime. Same exe-dir →
/// source-tree fallback as [`resolve_assets_mame_source_dir`].
pub fn resolve_docs_cores_dir() -> Option<PathBuf> {
    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            let p = exe_dir.join("docs").join("cores");
            if p.is_dir() {
                return Some(p);
            }
        }
    }
    let dev = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("docs")
        .join("cores");
    if dev.is_dir() {
        return Some(dev);
    }
    None
}

/// Read + parse `listxml-slim.json` and `history-slim.xml`, then
/// join the history descriptions onto the per-system L1 records via
/// machine_name. Returns the Vec the bake-on-launch path passes to
/// [`crate::library_db::LibraryDb::bake_system_info_mame`].
///
/// Missing slim files degrade gracefully: a missing listxml-slim.json
/// returns an empty Vec (no L1 layer); a missing history-slim.xml
/// just leaves the `description` field None on every row.
pub fn load_mame_records(
    listxml_path: &Path,
    history_path: &Path,
) -> Result<Vec<SystemInfoMame>, String> {
    let listxml_body = match std::fs::read_to_string(listxml_path) {
        Ok(b) => b,
        Err(e) => {
            log::warn!(
                "system_info: listxml-slim.json missing at {} ({e}); L1 layer is empty",
                listxml_path.display()
            );
            return Ok(Vec::new());
        }
    };
    let slim = parse_listxml_slim_json(&listxml_body)?;

    // Build the machine_name → description map. Missing history.xml
    // (the placeholder case) yields an empty map and every L1 row
    // ends up with `description: None`.
    let descriptions: HashMap<String, String> = match std::fs::read_to_string(history_path) {
        Ok(body) => parse_history_slim_xml(&body).unwrap_or_else(|e| {
            log::warn!(
                "system_info: history-slim.xml parse failed ({e}); descriptions empty"
            );
            HashMap::new()
        }),
        Err(e) => {
            log::info!(
                "system_info: history-slim.xml missing at {} ({e}); descriptions empty",
                history_path.display()
            );
            HashMap::new()
        }
    };

    let mut out = slim.systems;
    for row in &mut out {
        if let Some(name) = &row.machine_name {
            if let Some(desc) = descriptions.get(name) {
                row.description = Some(desc.clone());
            }
        }
    }
    Ok(out)
}

/// Walk every `docs/cores/<id>/system-info.yaml` under `dir` and
/// return the parsed L2 records. Silently skips per-system
/// directories that don't ship a `system-info.yaml` yet — v1 only
/// migrates 5 of 45 systems from the old stub data; the others
/// arrive over time.
pub fn load_curated_records(dir: &Path) -> Vec<SystemInfoCurated> {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) => {
            log::info!(
                "system_info: docs/cores dir not readable at {} ({e}); L2 layer is empty",
                dir.display()
            );
            return Vec::new();
        }
    };

    let mut out = Vec::new();
    for entry in entries.filter_map(|e| e.ok()) {
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if !file_type.is_dir() {
            continue;
        }
        let p = entry.path();
        let yaml_path = p.join("system-info.yaml");
        let Ok(meta) = std::fs::metadata(&yaml_path) else {
            continue;
        };
        if !meta.is_file() {
            continue;
        }
        let body = match std::fs::read_to_string(&yaml_path) {
            Ok(b) => b,
            Err(e) => {
                log::warn!(
                    "system_info: read failed for {}: {e}; skipping",
                    yaml_path.display()
                );
                continue;
            }
        };
        match parse_system_info_yaml(&body) {
            Ok(Some(rec)) => out.push(rec),
            Ok(None) => {}
            Err(e) => {
                log::warn!(
                    "system_info: parse failed for {}: {e}; skipping",
                    yaml_path.display()
                );
            }
        }
    }

    // Stable order — system_id alphabetical — so the bake produces
    // deterministic SQLite rowid sequences across runs (small win
    // for diff debugging when comparing two installs).
    out.sort_by(|a, b| a.system_id.cmp(&b.system_id));
    out
}

/// Slice 1 of the per-system descriptor consolidation
/// (`docs/PLANS/per-system-descriptors.md`). Walks both the legacy
/// `docs/cores/<id>/system-info.yaml` files AND any embedded
/// `system_info:` blocks in `config/systems/<id>/system.yaml` via the
/// supplied [`crate::system_registry::SystemRegistry`], merging both
/// sources by `system_id` — **registry wins** when a system has L2
/// data in both locations.
///
/// During Slice 1 the 3 pilot systems (GB, PSX, NDS) live in the
/// registry; the other 38 still live in docs/cores. Slice 2 migrates
/// the rest and removes the legacy walk.
///
/// Stable order: alphabetical by `system_id`, same as
/// [`load_curated_records`].
pub fn load_curated_records_with_registry(
    docs_cores_dir: &Path,
    registry: &crate::system_registry::SystemRegistry,
) -> Vec<SystemInfoCurated> {
    let mut by_id: HashMap<String, SystemInfoCurated> = HashMap::new();
    for rec in load_curated_records(docs_cores_dir) {
        by_id.insert(rec.system_id.clone(), rec);
    }
    for sys_id in registry.system_ids() {
        let Some(loaded) = registry.get(sys_id) else {
            continue;
        };
        if let Some(panel) = &loaded.descriptor.system_info {
            // Embedded block's system_id was validated against the
            // descriptor's id at registry load time
            // (EmbeddedSystemInfoIdMismatch hot-fail), so insert is safe.
            by_id.insert(panel.system_id.clone(), panel.clone());
        }
    }
    let mut out: Vec<SystemInfoCurated> = by_id.into_values().collect();
    out.sort_by(|a, b| a.system_id.cmp(&b.system_id));
    out
}

// =====================================================================
// Hash for bake-on-launch dirty detection (plan §5)
// =====================================================================

/// Hash the L1 + L2 source files so bake-on-launch can detect when a
/// rebake is needed. Combines:
///
/// - `listxml-slim.json` content (whole file)
/// - `history-slim.xml` content (whole file)
/// - every `docs/cores/<id>/system-info.yaml` (sorted by path so the
///   hash is stable across filesystems)
///
/// Returns a hex-encoded 16-char prefix of the SHA-1 — short enough
/// to store cheaply in the meta table, long enough that collisions
/// are statistically impossible within a single install's lifetime.
///
/// Missing files contribute the literal byte string `"MISSING:<path>"`
/// to the hash, so dropping a YAML or losing a slim file triggers a
/// rebake on the next launch.

fn hash_file_into<H: sha1::Digest>(hasher: &mut H, path: &Path) {
    match std::fs::read(path) {
        Ok(bytes) => {
            hasher.update(b"FILE:");
            hasher.update(bytes);
        }
        Err(_) => {
            hasher.update(b"MISSING:");
            hasher.update(path.to_string_lossy().as_bytes());
        }
    }
}

/// Slice 1 companion to [`hash_l1_l2_inputs`] that also folds every
/// `config/systems/<id>/{system,bios,games}.yaml` file into the hash.
/// Without this, edits to a pilot system's `system.yaml` (the new L2
/// source) wouldn't trip the bake-on-launch dirty check and the SQLite
/// `system_info_curated` table would lag the YAMLs across launches.
///
/// Returns the same shape as [`hash_l1_l2_inputs`] (16-char hex
/// prefix of SHA-1) so callers can swap between them without changing
/// the dirty-check comparison.
///
/// Falls back to [`hash_l1_l2_inputs`]'s output when `registry` has
/// no source root (the empty-registry case during pilot transition).
pub fn hash_l1_l2_inputs_with_registry(
    listxml_path: &Path,
    history_path: &Path,
    docs_cores_dir: &Path,
    registry: &crate::system_registry::SystemRegistry,
) -> String {
    use sha1::{Digest, Sha1};

    let mut hasher = Sha1::new();
    hash_file_into(&mut hasher, listxml_path);
    hash_file_into(&mut hasher, history_path);

    // Legacy docs/cores walk.
    let mut yamls: Vec<PathBuf> = match std::fs::read_dir(docs_cores_dir) {
        Ok(e) => e
            .filter_map(|x| x.ok())
            .filter(|x| x.file_type().map(|t| t.is_dir()).unwrap_or(false))
            .map(|x| x.path().join("system-info.yaml"))
            .filter(|p| std::fs::metadata(p).map(|m| m.is_file()).unwrap_or(false))
            .collect(),
        Err(_) => Vec::new(),
    };
    yamls.sort();
    for p in &yamls {
        hash_file_into(&mut hasher, p);
    }

    // Registry walk — each per-system folder under config/systems/
    // contributes its system.yaml + (optional) bios.yaml + games.yaml.
    // Walk via the registry's source_root so the loader's path
    // resolution stays the single source of truth (no duplicate
    // exe-dir / source-tree fallback logic here).
    if let Some(root) = registry.source_root() {
        let mut reg_paths: Vec<PathBuf> = Vec::new();
        if let Ok(entries) = std::fs::read_dir(root) {
            for entry in entries.flatten() {
                if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                    let folder = entry.path();
                    for filename in ["system.yaml", "bios.yaml", "games.yaml"] {
                        let candidate = folder.join(filename);
                        if std::fs::metadata(&candidate).map(|m| m.is_file()).unwrap_or(false) {
                            reg_paths.push(candidate);
                        }
                    }
                }
            }
        }
        reg_paths.sort();
        for p in &reg_paths {
            hash_file_into(&mut hasher, p);
        }
    }

    let digest = hasher.finalize();
    let hex: String = digest.iter().map(|b| format!("{b:02x}")).collect();
    hex[..16].to_string()
}

// =====================================================================
// Tests
// =====================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ---- L1 parser ---------------------------------------------------

    const SAMPLE_LISTXML_JSON: &str = r#"{
        "mame_version": "0.288",
        "systems": [
            {
                "system_id": "nes",
                "machine_name": "nes",
                "year": "1985",
                "manufacturer": "Nintendo",
                "cpu": "Ricoh RP2A03G @ 1.79 MHz",
                "sound": "Ricoh RP2A03G @ 1.79 MHz",
                "resolution": "256 × 240",
                "refresh_rate": "60.10 Hz",
                "max_players": 2,
                "peripheral_hints": ["joy", "lightgun"]
            },
            {
                "system_id": "tg16",
                "machine_name": "pce",
                "year": "1987",
                "manufacturer": "NEC / Hudson Soft",
                "peripheral_hints": ["joy"]
            }
        ]
    }"#;

    #[test]
    fn parse_listxml_yields_per_slug_records() {
        let slim = parse_listxml_slim_json(SAMPLE_LISTXML_JSON).unwrap();
        assert_eq!(slim.mame_version, "0.288");
        assert_eq!(slim.systems.len(), 2);
        let nes = &slim.systems[0];
        assert_eq!(nes.system_id, "nes");
        assert_eq!(nes.year.as_deref(), Some("1985"));
        assert_eq!(nes.max_players, Some(2));
        assert_eq!(nes.peripheral_hints, vec!["joy", "lightgun"]);
        let tg16 = &slim.systems[1];
        assert_eq!(tg16.system_id, "tg16");
        // Missing fields parse as None (e.g. cpu wasn't in the sample).
        assert!(tg16.cpu.is_none());
    }

    #[test]
    fn parse_listxml_empty_systems_array() {
        let slim = parse_listxml_slim_json(r#"{"mame_version": "0", "systems": []}"#).unwrap();
        assert!(slim.systems.is_empty());
    }

    // ---- L1 history.xml parser --------------------------------------

    const SAMPLE_HISTORY_XML: &str = r#"<?xml version="1.0"?>
<history version="2.87a" date="2026-04-11">
    <entry>
        <systems>
            <system name="nes" game="no" />
            <system name="nespal" game="no" />
        </systems>
        <text>
Console published 41 years ago.

Nintendo Entertainment System [NES] (c) 1985 Nintendo Co., Ltd.
        </text>
    </entry>
    <entry>
        <systems>
            <system name="pce" game="no" />
        </systems>
        <text>
PC Engine console description.
        </text>
    </entry>
</history>
"#;

    #[test]
    fn parse_history_yields_machine_keyed_map() {
        let m = parse_history_slim_xml(SAMPLE_HISTORY_XML).unwrap();
        assert_eq!(m.len(), 3, "nes + nespal + pce share the entries");
        let nes_desc = m.get("nes").unwrap();
        assert!(nes_desc.contains("Nintendo Entertainment System"));
        let nespal_desc = m.get("nespal").unwrap();
        assert_eq!(nes_desc, nespal_desc, "shared <systems> share the text");
        let pce_desc = m.get("pce").unwrap();
        assert!(pce_desc.contains("PC Engine"));
    }

    #[test]
    fn parse_history_placeholder_yields_empty_map() {
        // The header-only placeholder the extractor writes when no
        // history.xml was supplied — must parse to an empty map.
        let placeholder = r#"<?xml version="1.0" encoding="UTF-8"?>
<!-- placeholder -->
<history>
</history>
"#;
        let m = parse_history_slim_xml(placeholder).unwrap();
        assert!(m.is_empty());
    }

    // ---- L2 YAML parser ---------------------------------------------

    #[test]
    fn parse_yaml_full_record() {
        let yaml = r#"
system_id: snes
manufacturer: Nintendo
type: Home Console
generation: 4th Generation
release_date: "August 23, 1990"
discontinued: "September 25, 1997"
units_sold: "49.10 Million"
media: Cartridge
cpu: "Ricoh 5A22 @ 3.58 MHz"
sound: "Sony SPC700"
architecture: 16-Bit
max_players: "1-2 Players"
multiplayer: "Yes — 2 local; 5 via Multitap"
region: NTSC / PAL
peripherals:
  - name: SNES Controller
    glyph: "🎮"
  - name: Super Scope
    glyph: "🔫"
release_flag: "🇯🇵"
tagline: "16-BIT HOME CONSOLE"
blurb: "Nintendo's second home console."
sidebar_subline: "16-BIT · 1990"
meta:
  schema_version: 1
  last_updated: "2026-05-31"
"#;
        let rec = parse_system_info_yaml(yaml).unwrap().unwrap();
        assert_eq!(rec.system_id, "snes");
        assert_eq!(rec.manufacturer.as_deref(), Some("Nintendo"));
        assert_eq!(rec.system_type.as_deref(), Some("Home Console"));
        assert_eq!(rec.generation.as_deref(), Some("4th Generation"));
        assert_eq!(rec.cpu.as_deref(), Some("Ricoh 5A22 @ 3.58 MHz"));
        assert_eq!(rec.max_players.as_deref(), Some("1-2 Players"));
        assert_eq!(
            rec.multiplayer.as_deref(),
            Some("Yes — 2 local; 5 via Multitap")
        );
        assert_eq!(rec.peripherals.len(), 2);
        assert_eq!(rec.peripherals[0].name, "SNES Controller");
        assert_eq!(rec.peripherals[1].glyph, "🔫");
        assert_eq!(rec.release_flag.as_deref(), Some("🇯🇵"));
        assert_eq!(rec.meta.schema_version, 1);
        assert_eq!(rec.meta.last_updated.as_deref(), Some("2026-05-31"));
    }

    #[test]
    fn parse_yaml_minimal_record_only_system_id() {
        // A YAML with just `system_id` must parse cleanly — all
        // optional fields fall through to None, peripherals to empty
        // Vec, meta to default.
        let yaml = "system_id: gba\n";
        let rec = parse_system_info_yaml(yaml).unwrap().unwrap();
        assert_eq!(rec.system_id, "gba");
        assert!(rec.manufacturer.is_none());
        assert!(rec.peripherals.is_empty());
        assert_eq!(rec.meta.schema_version, CURRENT_SCHEMA_VERSION);
    }

    #[test]
    fn parse_yaml_empty_string_returns_none() {
        assert!(parse_system_info_yaml("").unwrap().is_none());
        assert!(parse_system_info_yaml("   \n\n  ").unwrap().is_none());
    }

    #[test]
    fn parse_yaml_malformed_returns_err() {
        // Missing mandatory system_id field — serde must surface the
        // error rather than silently producing a default record.
        let yaml = "manufacturer: Nintendo\n";
        assert!(parse_system_info_yaml(yaml).is_err());
    }

    // ---- Merge — field-typed precedence -----------------------------

    fn nes_mame_record() -> SystemInfoMame {
        SystemInfoMame {
            system_id: "nes".to_string(),
            machine_name: Some("nes".to_string()),
            year: Some("1985".to_string()),
            manufacturer: Some("Nintendo".to_string()),
            cpu: Some("Ricoh RP2A03G @ 1.79 MHz".to_string()),
            sound: Some("Ricoh RP2A03G @ 1.79 MHz".to_string()),
            resolution: Some("256 × 240".to_string()),
            refresh_rate: Some("60.10 Hz".to_string()),
            max_players: Some(2),
            peripheral_hints: vec!["joy".to_string(), "lightgun".to_string()],
            description: Some("Nintendo Entertainment System [NES] (c) 1985 Nintendo.".to_string()),
        }
    }

    fn nes_curated_record() -> SystemInfoCurated {
        SystemInfoCurated {
            system_id: "nes".to_string(),
            manufacturer: Some("Nintendo".to_string()),
            system_type: Some("Home Console".to_string()),
            generation: Some("3rd Generation".to_string()),
            release_date: Some("July 15, 1983".to_string()),
            sound: Some("Ricoh 2A03 APU".to_string()), // polishes L1
            max_players: Some("1-2 Players".to_string()),
            multiplayer: Some("Yes".to_string()),
            architecture: Some("8-Bit".to_string()),
            peripherals: vec![Peripheral {
                name: "NES Controller".to_string(),
                glyph: "🎮".to_string(),
            }],
            blurb: Some("Nintendo's flagship 1980s console.".to_string()),
            ..Default::default()
        }
    }

    #[test]
    fn merge_l1_only_no_l2_no_l3_fills_what_mame_has() {
        let m = nes_mame_record();
        let merged = merge_system_info("nes", Some(&m), None, &SystemInfoOverride::default());
        assert_eq!(merged.system_id, "nes");
        assert_eq!(merged.manufacturer.as_deref(), Some("Nintendo"));
        assert_eq!(merged.cpu.as_deref(), Some("Ricoh RP2A03G @ 1.79 MHz"));
        // L1's u32 max_players formats to a string via the bridge.
        assert_eq!(merged.max_players.as_deref(), Some("Up to 2 Players"));
        // L1 has no L2-only fields → all None.
        assert!(merged.system_type.is_none());
        assert!(merged.generation.is_none());
        assert!(merged.blurb.is_none());
        assert!(merged.peripherals.is_empty());
        // peripheral_hints carry through from L1.
        assert_eq!(merged.peripheral_hints, vec!["joy", "lightgun"]);
        // description from L1's history.xml prose.
        assert!(merged
            .description
            .as_deref()
            .unwrap()
            .contains("Nintendo Entertainment System"));
        // release_date falls back to L1's bare year when L2 absent.
        assert_eq!(merged.release_date.as_deref(), Some("1985"));
        assert!(!merged.has_local_edits);
    }

    #[test]
    fn merge_l2_polishes_l1_fields() {
        let m = nes_mame_record();
        let c = nes_curated_record();
        let merged = merge_system_info("nes", Some(&m), Some(&c), &SystemInfoOverride::default());
        // L2 polishes sound; L1's value drops.
        assert_eq!(merged.sound.as_deref(), Some("Ricoh 2A03 APU"));
        // L2 polishes max_players to free-form string.
        assert_eq!(merged.max_players.as_deref(), Some("1-2 Players"));
        // L2 owns the operator-facing peripherals list.
        assert_eq!(merged.peripherals.len(), 1);
        assert_eq!(merged.peripherals[0].name, "NES Controller");
        // L2 supplies fields L1 doesn't have.
        assert_eq!(merged.system_type.as_deref(), Some("Home Console"));
        assert_eq!(merged.generation.as_deref(), Some("3rd Generation"));
        assert_eq!(merged.architecture.as_deref(), Some("8-Bit"));
        // L2's release_date wins over L1's year.
        assert_eq!(merged.release_date.as_deref(), Some("July 15, 1983"));
        // L1 still carries cpu (L2 left it None).
        assert_eq!(merged.cpu.as_deref(), Some("Ricoh RP2A03G @ 1.79 MHz"));
        // peripheral_hints still carry from L1.
        assert_eq!(merged.peripheral_hints, vec!["joy", "lightgun"]);
    }

    #[test]
    fn merge_l3_wins_over_l2_and_l1() {
        let m = nes_mame_record();
        let c = nes_curated_record();
        let ov = SystemInfoOverride {
            blurb: Some("Operator's own NES take.".to_string()),
            cpu: Some("MOS 6502-derivative".to_string()),
            peripherals: Some(vec![]), // operator clears the list
            ..Default::default()
        };
        let merged = merge_system_info("nes", Some(&m), Some(&c), &ov);
        assert_eq!(merged.blurb.as_deref(), Some("Operator's own NES take."));
        assert_eq!(merged.cpu.as_deref(), Some("MOS 6502-derivative"));
        // L3 cleared peripherals → empty Vec, not L2's list.
        assert!(merged.peripherals.is_empty());
        // L2's sound polish still wins where L3 didn't touch.
        assert_eq!(merged.sound.as_deref(), Some("Ricoh 2A03 APU"));
        assert!(merged.has_local_edits);
    }

    #[test]
    fn merge_no_layers_returns_empty_record() {
        // Pathological case: system_id with no L1, no L2, no L3.
        // Frontend still receives a record (with all fields None) so
        // the panel can render "—" everywhere rather than blowing up.
        let merged = merge_system_info("imaginary", None, None, &SystemInfoOverride::default());
        assert_eq!(merged.system_id, "imaginary");
        assert!(merged.manufacturer.is_none());
        assert!(merged.peripherals.is_empty());
        assert!(merged.peripheral_hints.is_empty());
        assert!(!merged.has_local_edits);
    }

    #[test]
    fn merge_l2_only_no_l1_works_for_systems_mame_doesnt_cover() {
        // DOSBox / ScummVM / 3DO / MSX / MSX2 path — no L1 record at
        // all; L2 carries everything.
        let c = SystemInfoCurated {
            system_id: "dosbox".to_string(),
            manufacturer: Some("DOSBox Team".to_string()),
            system_type: Some("Emulator".to_string()),
            blurb: Some("PC DOS gaming environment.".to_string()),
            ..Default::default()
        };
        let merged = merge_system_info("dosbox", None, Some(&c), &SystemInfoOverride::default());
        assert_eq!(merged.system_id, "dosbox");
        assert_eq!(merged.manufacturer.as_deref(), Some("DOSBox Team"));
        assert_eq!(merged.system_type.as_deref(), Some("Emulator"));
        assert_eq!(merged.blurb.as_deref(), Some("PC DOS gaming environment."));
        assert!(merged.cpu.is_none());
        assert!(merged.description.is_none());
        assert!(merged.peripheral_hints.is_empty());
    }

    #[test]
    fn merge_l3_only_no_l1_no_l2_records_operator_edits() {
        // Operator authors notes for a system with no L1+L2 records
        // (a system we don't curate yet). Merged record reflects the
        // edits + flips has_local_edits.
        let ov = SystemInfoOverride {
            blurb: Some("My description.".to_string()),
            ..Default::default()
        };
        let merged = merge_system_info("hypothetical", None, None, &ov);
        assert_eq!(merged.blurb.as_deref(), Some("My description."));
        assert!(merged.has_local_edits);
    }

    // ---- SystemInfoOverride::is_empty -------------------------------

    #[test]
    fn override_default_is_empty() {
        assert!(SystemInfoOverride::default().is_empty());
    }

    #[test]
    fn override_with_one_field_is_not_empty() {
        let ov = SystemInfoOverride {
            blurb: Some("set".to_string()),
            ..Default::default()
        };
        assert!(!ov.is_empty());
    }

    #[test]
    fn override_with_empty_peripherals_vec_is_not_empty() {
        // Some(vec![]) means "operator says no peripherals" — distinct
        // from None ("no override"). is_empty must respect that
        // (otherwise the set/delete path eats the explicit clear).
        let ov = SystemInfoOverride {
            peripherals: Some(vec![]),
            ..Default::default()
        };
        assert!(!ov.is_empty());
    }

    // ---- Hash --------------------------------------------------------

    #[test]
    fn load_curated_records_legacy_docs_cores_is_now_empty() {
        // Slice 2 Phase B (2026-06-02): every system-info.yaml under
        // docs/cores/<id>/ has been migrated into
        // config/systems/<id>/system.yaml's embedded `system_info:`
        // block. The legacy walk now produces zero records; the
        // `load_curated_records_with_registry` path is the live
        // L2 source (covered by `registry_load_finds_all_v1_panel_systems`
        // below).
        let dir = resolve_docs_cores_dir()
            .expect("docs/cores must resolve under cargo test");
        let records = load_curated_records(&dir);
        assert!(
            records.is_empty(),
            "docs/cores walk should be empty post-Slice-2 Phase B; got: {:?}",
            records.iter().map(|r| &r.system_id).collect::<Vec<_>>()
        );
    }

    #[test]
    fn registry_load_finds_all_v1_panel_systems() {
        // Slice 2 Phase B (2026-06-02): the pre-Slice-1 v1 lineup of
        // hand-authored L2 entries (snes / nes / genesis / psx / gb)
        // all surface through the registry path now that Phase B
        // moved snes/nes/genesis to config/systems alongside the gb/
        // psx/nds Slice 1 pilots.
        let dir = resolve_docs_cores_dir()
            .expect("docs/cores must resolve under cargo test");
        let registry = crate::system_registry::SystemRegistry::load_default();
        let records = load_curated_records_with_registry(&dir, &registry);
        for required in &["snes", "nes", "genesis", "psx", "gb"] {
            assert!(
                records.iter().any(|r| r.system_id == *required),
                "missing required L2 record for {required} via registry path"
            );
        }
        // Spot-check that fields actually populated — catch the case
        // where a YAML parses but every field is None (broken renames).
        let snes = records
            .iter()
            .find(|r| r.system_id == "snes")
            .expect("snes record");
        assert_eq!(snes.manufacturer.as_deref(), Some("Nintendo"));
        assert_eq!(snes.system_type.as_deref(), Some("Home Console"));
        assert_eq!(snes.architecture.as_deref(), Some("16-Bit"));
        assert!(snes.blurb.as_deref().unwrap().contains("Nintendo"));
        assert!(!snes.peripherals.is_empty());
    }

    #[test]
    fn registry_load_finds_gb_via_config_systems_path() {
        // Slice 1 Phase B (2026-06-02) — `gb`'s L2 record moved from
        // docs/cores/gb/system-info.yaml into the embedded
        // `system_info:` block of config/systems/gb/system.yaml.
        // load_curated_records_with_registry must find it via the
        // registry path. Validates the migration end-to-end.
        let dir = resolve_docs_cores_dir()
            .expect("docs/cores must resolve under cargo test");
        let registry = crate::system_registry::SystemRegistry::load_default();
        let records = load_curated_records_with_registry(&dir, &registry);
        let gb = records
            .iter()
            .find(|r| r.system_id == "gb")
            .expect("gb L2 record must surface via config/systems/gb/system.yaml");
        assert_eq!(gb.manufacturer.as_deref(), Some("Nintendo"));
        assert_eq!(gb.system_type.as_deref(), Some("Handheld"));
        assert_eq!(gb.architecture.as_deref(), Some("8-Bit"));
        assert!(
            gb.blurb.as_deref().unwrap().contains("Tetris"),
            "gb blurb should mention Tetris per the migrated content; got {:?}",
            gb.blurb
        );
        assert!(!gb.peripherals.is_empty(), "gb peripherals must populate");

        // Also confirm gb does NOT appear in the legacy
        // docs/cores walk anymore (regression guard against a stray
        // re-creation of docs/cores/gb/system-info.yaml in a future
        // commit).
        let legacy = load_curated_records(&dir);
        assert!(
            !legacy.iter().any(|r| r.system_id == "gb"),
            "gb must not be in docs/cores/ after the Slice 1 Phase B migration"
        );
    }

    #[test]
    fn registry_load_finds_psx_via_config_systems_path() {
        // Slice 1 Phase C (2026-06-02) — `psx`'s L2 record moved from
        // docs/cores/psx/system-info.yaml into the embedded
        // `system_info:` block of config/systems/psx/system.yaml.
        let dir = resolve_docs_cores_dir()
            .expect("docs/cores must resolve under cargo test");
        let registry = crate::system_registry::SystemRegistry::load_default();
        let records = load_curated_records_with_registry(&dir, &registry);
        let psx = records
            .iter()
            .find(|r| r.system_id == "psx")
            .expect("psx L2 record must surface via config/systems/psx/system.yaml");
        assert_eq!(psx.manufacturer.as_deref(), Some("Sony"));
        assert_eq!(psx.system_type.as_deref(), Some("Home Console"));
        assert_eq!(psx.architecture.as_deref(), Some("32-Bit"));
        assert!(
            psx.blurb.as_deref().unwrap().contains("3D"),
            "psx blurb should mention 3D per the migrated content; got {:?}",
            psx.blurb
        );

        // Regression guard: psx must NOT be in the legacy docs/cores walk.
        let legacy = load_curated_records(&dir);
        assert!(
            !legacy.iter().any(|r| r.system_id == "psx"),
            "psx must not be in docs/cores/ after the Slice 1 Phase C migration"
        );
    }

    #[test]
    fn hash_changes_when_a_file_changes() {
        // Construct two tiny temp trees with the same files but one
        // differing byte, confirm the hash diverges. This is the
        // bake-on-launch rebake trigger. Uses
        // `hash_l1_l2_inputs_with_registry` (Slice 2 Phase D deleted
        // the registry-less variant); an empty registry just means
        // the hash folds the slim files alone, which is enough to
        // exercise the byte-change-flips-hash invariant.
        let tmp = std::env::temp_dir().join(format!("oa-sysinfo-hash-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        let listxml = tmp.join("listxml.json");
        let history = tmp.join("history.xml");
        let cores = tmp.join("cores");
        std::fs::create_dir_all(&cores).unwrap();

        let empty_registry = crate::system_registry::SystemRegistry::empty();
        std::fs::write(&listxml, "{}").unwrap();
        std::fs::write(&history, "<history/>").unwrap();
        let h1 = hash_l1_l2_inputs_with_registry(&listxml, &history, &cores, &empty_registry);
        std::fs::write(&listxml, "{ }").unwrap(); // single byte change
        let h2 = hash_l1_l2_inputs_with_registry(&listxml, &history, &cores, &empty_registry);
        assert_ne!(h1, h2, "single-byte change in slim must flip the hash");

        // Cleanup — best-effort.
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
