[package]
name = "oa-render"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
oa-core           = { workspace = true }
wgpu              = { workspace = true }
raw-window-handle = { workspace = true }
pollster          = { workspace = true }
bytemuck          = { workspace = true }
log               = { workspace = true }
thiserror         = { workspace = true }
